// Today's jargon on screen, as "copy path: avoid-word" (T8.2). The plain-words check
// fails on any new one, and on any entry here that's been fixed: each UI refresh
// slice removes what it rewords, and the list is empty by v1.0.y's gate.
export const PENDING: readonly string[] = [
  "overlay:gizmos.borderGlobal: --name",
  "overlay:gizmos.borderNotToken: token",
  "overlay:gizmos.noRadiusToken: token",
  "overlay:gizmos.radiusGlobal: --name",
  "overlay:gizmos.radiusGlobal: derived",
  "overlay:gizmos.spacingGlobal: --name",
  "overlay:gizmos.typeGlobal: --name",
  "overlay:overlay.lockedKinds.conditional: conditional",
  "overlay:overlay.lockedKinds.expression: {…}",
  "overlay:overlay.lockedKinds.fragment: <>…</>",
  "overlay:overlay.lockedKinds.map: .map()",
  "overlay:overlay.lockedKinds.map: map",
  "renderer:app.cantDropThere: data-ui-id",
  "renderer:app.cantMoveThere: data-ui-id",
  "renderer:app.classEdits.locked: locked",
  "renderer:app.classEdits.locked: locked block",
  "renderer:app.classEdits.noId: data-ui-id",
  "renderer:app.colourMode: colour mode",
  "renderer:app.info: node",
  "renderer:app.interactMode: interact mode",
  "renderer:app.noPageFile: page file",
  "renderer:app.selectMode: select mode",
  "renderer:app.tabs.pass: pass",
  "renderer:app.tabs.tokens: tokens",
  "renderer:app.tabs.violations: violations",
  "renderer:canvas.server.crashed: dev server",
  "renderer:canvas.server.failed: dev server",
  "renderer:canvas.server.starting: dev server",
  "renderer:canvas.server.stopped: dev server",
  "renderer:canvas.veil: locked",
  "renderer:canvas.withAgent: handoff #",
  "renderer:canvas.withAgent: with agent",
  "renderer:colour.instanceNote: override",
  "renderer:colour.instanceNote: violations",
  "renderer:colour.instanceTitle: violation",
  "renderer:colour.scope: scope",
  "renderer:colour.token: token",
  "renderer:devServer.title: dev server",
  "renderer:layers.locked: locked",
  "renderer:loop.busy.revert: pass",
  "renderer:loop.handOffHint: handoff #",
  "renderer:loop.withAgent: handoff #",
  "renderer:loop.withAgent: with agent",
  "renderer:nodes.noId: data-ui-id",
  "renderer:nodes.noIds: data-ui-id",
  "renderer:notes.agentReply: pass",
  "renderer:notes.attachNeedsId: data-ui-id",
  "renderer:notes.cantPin: data-ui-id",
  "renderer:notes.replyPass: pass",
  "renderer:pages.dynamic: route",
  "renderer:pages.path: path",
  "renderer:pages.unreadable: page file",
  "renderer:palette.groupList: components",
  "renderer:palette.title: palette",
  "renderer:pass.diffTitle: diff",
  "renderer:pass.empty: pass",
  "renderer:pass.emptyWithAgent: pass",
  "renderer:pass.gaveId: id",
  "renderer:pass.groups.breaches: contract breaches",
  "renderer:pass.groups.locked: locked",
  "renderer:pass.groups.locked: new locked blocks",
  "renderer:pass.groups.repaired: repaired",
  "renderer:pass.groups.violations: violations",
  "renderer:pass.inlineStyle: {…}",
  "renderer:pass.noSummary: diff",
  "renderer:pass.numbered: pass",
  "renderer:pass.reminted: re-minted",
  "renderer:pass.revertButton: pass",
  "renderer:pass.revertButton: revert pass",
  "renderer:pass.revertConfirm: handoff #",
  "renderer:pass.revertTitle: pass",
  "renderer:pass.revertTitle: revert pass",
  "renderer:pass.tasks: task",
  "renderer:pass.title: pass",
  "renderer:properties.noId: data-ui-id",
  "renderer:properties.stack: stack",
  "renderer:selection.agentLogic: agent logic",
  "renderer:selection.id: id",
  "renderer:selection.locked: locked",
  "renderer:tokens.cantDetach: detached",
  "renderer:tokens.derivedTitle: derived",
  "renderer:tokens.derivedTitle: tokens",
  "renderer:tokens.detachTitle: formula",
  "renderer:tokens.detached: detached",
  "renderer:tokens.filterLabel: tokens",
  "renderer:tokens.title: tokens",
  "renderer:viewSource.hide: source",
  "renderer:viewSource.show: source",
  "renderer:viewSource.show: view source",
  "renderer:viewSource.title: source",
  "renderer:violations.empty: tokens",
  "renderer:violations.inAgentCode: keep",
  "renderer:violations.keep: keep",
  "renderer:violations.keepTitle: acknowledge",
  "renderer:violations.promote: promote",
  "renderer:violations.promoteForm: promote",
  "renderer:violations.promoteForm: token",
  "renderer:violations.property.other: arbitrary value",
  "renderer:violations.title: violations",
  "renderer:violations.tokenName: token",
];
