/**
 * Every word the renderer shows on screen (T8.1, docs/ui-refresh-spec.md §5).
 * Panels read their text from here, and so do the e2e helpers, so a wording
 * change is made once. Templated text is a function of what it shows.
 */

import type { ReasonCode } from "@skeleton/app-main/ipc";

/** What a reason's sentence can name, already in plain words (messages.ts fills it in). */
export interface Named {
  /** An element, by its element name. */
  el: string;
  /** A page, by its page name. */
  page: string;
  /** A web address. */
  path: string;
  /** A page or project name the user typed. */
  name: string;
  /** A theme value, by its theme value name. */
  theme: string;
  round: number;
  max: number;
  /** An undo step's label. */
  edit: string;
  direction: "undo" | "redo";
  /** A folder, by its own name. */
  folder: string;
  /** The web address a page's address must start with. */
  parent: string;
  /** The agent code an element is inside, by its kind ("repeated list"); empty when not known. */
  around: string;
}

const count = (n: number) => (n > 0 ? ` (${n})` : "");
/** `word` or `plural` (default `word` + "s") for `n`. */
const plural = (n: number, word: string, many = `${word}s`) => (n === 1 ? word : many);

/** Why an element added by the agent can't be changed until Take back gives it a name Skeleton can find. */
const OUTSIDE = "it was added outside Skeleton, and Skeleton will recognise it after the next Take back.";
const OUTSIDE_PARENT = "was added outside Skeleton, and Skeleton will recognise it after the next Take back.";

export const copy = {
  /**
   * The plain sentence for every reason code (ADR 013, spec §4): what happened, then
   * what to do. Refusals and problems; anything else gets `fault`.
   */
  messages: {
    "inside-agent-code": (n) =>
      n.around
        ? `Can't change ${n.el}: it's inside agent code (${n.around}). You can move or delete the whole ${n.around} instead.`
        : `Can't change ${n.el}: it's inside agent code. You can move or delete the whole agent code instead.`,
    "is-agent-code": (n) => `Can't change ${n.el}: it's agent code, so Skeleton won't rewrite it. You can move or delete it whole.`,
    "agent-control": (n) => `Can't change that setting of ${n.el}: the agent's code decides it.`,
    "agent-style": (n) => `Can't restyle ${n.el}: the agent's code decides its look. Add a note to ask the agent.`,
    "agent-value": () => "Can't edit this text: the agent's code fills it in.",
    "text-has-elements": (n) => `Can't edit the text of ${n.el} as a whole: it holds other elements. Edit their text instead.`,
    "text-has-comment": () => "Can't edit this text here: the agent left a remark in it. Ask the agent to change it.",
    "text-too-long": (n) => `That text is too long. Use at most ${n.max} characters.`,
    "element-gone": () => "Can't do that: the element isn't on the page any more.",
    "move-into-itself": (n) => `Can't move ${n.el} into itself.`,
    "next-to-text": (n) => `Can't drop there: ${n.el} holds text, so nothing can go inside it.`,
    "with-agent": () => "The project is with the agent. Take it back first.",
    "edit-undone": () => "Skeleton undid that change because it would have broken your app. Nothing was changed.",
    "nothing-to-undo": (n) => `There's nothing to ${n.direction}.`,
    "changed-since": (n) =>
      `Can't ${n.direction} "${n.edit}": the ${n.page} page has changed since then, probably by the agent. ${n.direction === "undo" ? "Undoing" : "Redoing"} now would lose that change.`,
    "bad-web-address": () => "A web address uses lowercase words and dashes, like /orders or /orders/archive.",
    "web-address-taken": (n) => `There's already a page at ${n.path}. Pick another web address.`,
    "web-address-outside": (n) => `This page's web address has to start with ${n.parent}.`,
    "bad-page-name": () => "A page name starts with a letter and uses only letters, numbers and spaces, like Order history.",
    "page-name-taken": (n) => `There's already a page called ${n.name}. Pick another name.`,
    "page-name-in-code": () => "Can't use that name: the page's code already uses it. Pick another name.",
    "page-file-taken": (n) => `There's already a page called ${n.page}. Pick another name.`,
    "only-page": () => "Can't delete the only page. Add another page first.",
    "page-used-elsewhere": (n) => `Can't do that to the ${n.page} page: other parts of your app use it. Ask the agent to remove those first.`,
    "page-has-subpages": (n) => `Can't do that to the page at ${n.path}: it has pages inside it. Ask the agent to change it.`,
    "page-is-default": () => "Can't change this page's web address: it shares the web address of the pages around it.",
    "page-not-renamable": () => "Can't rename this page here: the agent set it up in a way Skeleton can't change. Ask the agent to rename it.",
    "page-missing": () => "That page isn't in your app any more.",
    "page-unreadable": (n) => `Skeleton can't read the ${n.page} page right now, so it can't be changed.`,
    "pages-unreadable": () => "Skeleton can't read your app's list of pages, so pages can't be changed right now.",
    "theme-unreadable": () => "Skeleton can't read your app's theme right now.",
    "bad-theme-value": (n) => `That isn't a value ${n.theme} can use. Type one value, like 12px or #3366cc.`,
    "theme-value-twice": (n) => `Can't change ${n.theme}: the theme sets it in more than one place.`,
    "theme-value-missing": (n) => `Can't change ${n.theme}: it isn't in the theme any more.`,
    "theme-name-taken": (n) => `There's already a theme value called ${n.theme}. Pick another name.`,
    "off-theme-moved": () => "That value has moved since the list was made. Try again.",
    "off-theme-in-agent-code": () => "Can't change this value: it's in agent code. Leave it as is, or ask the agent.",
    "already-handed-off": (n) => `The project is already with the agent (round ${n.round}). Take it back first.`,
    "not-handed-off": () => "There's nothing to take back: the project isn't with the agent.",
    "nothing-to-undo-agent": () => "There's no agent's work to undo: the last step wasn't a take back.",
    "duplicate-ids": () => "Can't hand off yet: two elements look the same to Skeleton, so it can't tell them apart.",
    "build-broken": () => "Can't hand off: your app has a problem in its code and won't start.",
    "file-unreadable": () => "Skeleton can't read one of your app's pages, so it can't go on. Ask the agent to fix it, then try again. Nothing was changed.",
    "notes-unreadable": () => "Skeleton can't read your notes. Ask the agent to fix them, then try again. Nothing was changed.",
    "note-element-gone": () => "Can't pin the note there: that element isn't in your app any more.",
    "not-a-skeleton-project": (n) => `${n.folder} wasn't made with Skeleton, so it can't be opened here.`,
    "bad-project-name": () => "A project name starts with a letter or number, and uses letters, numbers, spaces and dashes.",
    "project-exists": (n) => `There's already a folder called ${n.folder} there. Pick another name or place.`,
    "folder-missing": () => "That folder isn't there any more. Choose another place.",
    "create-failed": () => "Skeleton couldn't create the project. Nothing was left behind.",
  } satisfies Record<ReasonCode, (n: Named) => string>,
  /**
   * The name tables (spec §6): theme values, settings and their options, agent
   * controls and element parts, in plain words. names.ts applies them, with the
   * fallback rules for anything not listed.
   */
  names: {
    theme: {
      "--background": "Page background",
      "--foreground": "Text",
      "--card": "Card background",
      "--card-foreground": "Text on cards",
      "--popover": "Menu background",
      "--popover-foreground": "Text in menus",
      "--primary": "Main colour",
      "--primary-foreground": "Text on main colour",
      "--secondary": "Second colour",
      "--secondary-foreground": "Text on second colour",
      "--muted": "Quiet background",
      "--muted-foreground": "Quiet text",
      "--accent": "Hover background",
      "--accent-foreground": "Text on hover",
      "--destructive": "Danger colour",
      "--border": "Lines and borders",
      "--input": "Text field borders",
      "--ring": "Focus outline",
      "--sidebar": "Sidebar background",
      "--sidebar-foreground": "Text in sidebar",
      "--sidebar-primary": "Sidebar main colour",
      "--sidebar-primary-foreground": "Text on sidebar main colour",
      "--sidebar-accent": "Sidebar hover background",
      "--sidebar-accent-foreground": "Text on sidebar hover",
      "--sidebar-border": "Sidebar lines",
      "--sidebar-ring": "Sidebar focus outline",
      "--radius": "Corner radius",
      "--radius-xs": "Tiny corners",
      "--radius-sm": "Small corners",
      "--radius-md": "Medium corners",
      "--radius-lg": "Large corners",
      "--radius-xl": "Extra-large corners",
      "--radius-button": "Button corners",
      "--radius-input": "Text field corners",
      "--radius-card": "Card corners",
      "--radius-dialog": "Dialog corners",
      "--radius-popover": "Menu corners",
      "--radius-badge": "Badge corners",
      "--type-base": "Text size",
      "--type-ratio": "Text size step",
      "--text-xs": "Smallest text",
      "--text-sm": "Small text",
      "--text-base": "Body text",
      "--text-lg": "Large text",
      "--text-xl": "Small heading",
      "--text-2xl": "Heading",
      "--text-3xl": "Large heading",
      "--text-4xl": "Largest heading",
      "--border-width": "Line thickness",
      "--spacing": "Spacing unit",
      "--font-sans": "Text font",
      "--font-mono": "Code font",
    } as Record<string, string>,
    /** A theme value someone else added: its name as words. */
    themeFallback: { corners: (words: string) => `${words} corners`, text: (words: string) => `${words} text` },
    /** Setting labels: by element where they differ, else for every element. */
    settings: {
      variant: "Style",
      size: "Size",
      type: "Kind of text",
      placeholder: "Hint text",
      rows: "Height in lines",
      disabled: "Greyed out",
      defaultChecked: "Starts ticked",
      defaultValue: "Starts with",
      value: "Value",
      position: "List opens",
      orientation: "Direction",
      direction: "Arrange",
      defaultOpen: "Starts open",
      showCloseButton: "Close button",
      side: "Opens from",
      align: "Line up with button",
      collapsible: "When closed",
      isActive: "Shown as current page",
    } as Record<string, string>,
    settingsFor: {
      Button: { type: "In a form" },
      Switch: { defaultChecked: "Starts on" },
      Tabs: { defaultValue: "Tab shown first" },
      TabsTrigger: { value: "Tab link name" },
      TabsContent: { value: "Tab link name" },
      Sidebar: { side: "Side" },
    } as Record<string, Record<string, string>>,
    /** Options of a setting: by element where they differ, else for every element. */
    options: {
      variant: { default: "Standard", destructive: "Danger", outline: "Outlined", secondary: "Subtle", ghost: "No background", link: "Link" },
      size: { default: "Medium", xs: "Extra small", sm: "Small", lg: "Large", icon: "Icon only", "icon-xs": "Icon only, extra small", "icon-sm": "Icon only, small", "icon-lg": "Icon only, large" },
      type: { text: "Text", email: "Email address", password: "Password", number: "Number", search: "Search", tel: "Phone number", url: "Web link", date: "Date" },
      position: { "item-aligned": "Over the field", popper: "Below the field" },
      orientation: { horizontal: "Across", vertical: "Down" },
      direction: { vertical: "Down", horizontal: "Across" },
      side: { top: "Top", right: "Right", bottom: "Bottom", left: "Left" },
      align: { start: "Start", center: "Centre", end: "End" },
      collapsible: { offcanvas: "Slides away", icon: "Shrinks to icons", none: "Always open" },
    } as Record<string, Record<string, string>>,
    optionsFor: {
      Button: { type: { submit: "Sends the form", reset: "Clears the form", button: "Does nothing by itself" } },
      TabsList: { variant: { default: "Boxed", line: "Underlined" } },
      Sidebar: { variant: { sidebar: "Attached", floating: "Floating", inset: "Inset" } },
    } as Record<string, Record<string, Record<string, string>>>,
    /** Settings never shown. */
    hiddenSettings: ["asChild"] as readonly string[],
    /** Layout settings, by the palette's label for them. */
    layout: {
      Gap: "Space between items",
      Padding: "Inner space: all sides",
      "Padding X": "Inner space: sides",
      "Padding Y": "Inner space: top and bottom",
      Align: "Line up",
      Justify: "Spread",
      Wrap: "Wrap onto new lines",
      Columns: "Columns",
    } as Record<string, string>,
    layoutOptions: {
      "—": "Not set",
      Center: "Centre",
      Baseline: "Text baseline",
      "No wrap": "Don't wrap",
      Wrap: "Wrap",
    } as Record<string, string>,
    /** What the agent's code decides about an element, read-only. */
    agentControls: {
      onClick: "What happens on click",
      onChange: "What happens when it changes",
      onValueChange: "What happens when it changes",
      onCheckedChange: "What happens when it's ticked",
      onSubmit: "What happens when the form is sent",
      onOpenChange: "What happens when it opens or closes",
      value: "Current value",
      checked: "Ticked or not",
      open: "Open or not",
      href: "Where it goes",
      to: "Where it goes",
      disabled: "When it's greyed out",
      className: "Its look (decided by the agent's code)",
      style: "Its look (decided by the agent's code)",
      src: "Image",
      alt: "Image description",
      children: "Its content",
    } as Record<string, string>,
    hiddenControls: ["key", "ref"] as readonly string[],
    agentControlOn: (words: string) => `What happens on ${words}`,
    /** Element kinds on screen: components and their parts, layout, and plain HTML. */
    elements: {
      Grid: "Grid",
      Container: "Page width",
      Spacer: "Push apart",
      Input: "Text field",
      Textarea: "Text box",
      Select: "Pick list",
      SelectTrigger: "Pick list button",
      SelectValue: "Pick list value",
      SelectContent: "Pick list options",
      SelectItem: "Option",
      DialogContent: "Dialog box",
      DialogTrigger: "Opens dialog",
      Sheet: "Side panel",
      SheetContent: "Side panel box",
      SheetTrigger: "Opens side panel",
      SheetHeader: "Side panel header",
      SheetTitle: "Side panel title",
      SheetDescription: "Side panel description",
      DropdownMenu: "Menu",
      DropdownMenuTrigger: "Opens menu",
      DropdownMenuContent: "Menu items",
      DropdownMenuItem: "Menu item",
      DropdownMenuLabel: "Menu label",
      DropdownMenuSeparator: "Menu separator",
      TabsList: "Tab bar",
      TabsTrigger: "Tab",
      TabsContent: "Tab content",
      AvatarFallback: "Avatar initials",
      SidebarProvider: "Sidebar area",
      SidebarInset: "Main area beside sidebar",
      Toaster: "Pop-up messages",
      h1: "Heading",
      h2: "Heading",
      h3: "Heading",
      h4: "Heading",
      h5: "Heading",
      h6: "Heading",
      p: "Text",
      span: "Text",
      strong: "Bold text",
      em: "Italic text",
      a: "Link",
      img: "Image",
      div: "Box",
      section: "Section",
      header: "Header",
      footer: "Footer",
      main: "Main area",
      nav: "Navigation",
      aside: "Side area",
      ul: "List",
      ol: "Numbered list",
      li: "List item",
      form: "Form",
      label: "Label",
      button: "Button",
      input: "Text field",
      textarea: "Text box",
      select: "Pick list",
      table: "Table",
      thead: "Table header",
      tbody: "Table body",
      tr: "Table row",
      th: "Table heading",
      td: "Table cell",
    } as Record<string, string>,
    /** A Stack is a Column or a Row, by how it arranges its items. */
    column: "Column",
    row: "Row",
    /** A Column or Row named without its node. */
    stack: "Column or row",
    /** Agent code that isn't an element of its own, by what it does. */
    agentKinds: {
      map: "Repeated list",
      conditional: "Shows sometimes",
      expression: "Agent value",
      fragment: "Group",
      spread: "Agent element",
    } as Record<string, string>,
    agentComponent: (name: string) => `Agent component: ${name}`,
    agentElement: "Agent element",
    withText: (kind: string, text: string) => `${kind} "${text}"`,
  },
  /** Anything without a reason: only a Skeleton bug could cause it. */
  fault: {
    unchanged: "Skeleton couldn't do that. Nothing in your project was changed.",
    unknown: "Skeleton couldn't do that. Something went wrong; see Details.",
  },
  details: {
    show: "Details",
    hide: "Hide details",
    copy: "Copy details",
    copied: "Copied",
    /** The block Copy details puts on the clipboard, for pasting to the agent. */
    block: (b: { tried: string; page: string | null; id: string | null; code: string | null; message: string }) =>
      [
        `Skeleton couldn't do this: ${b.tried}`,
        b.page ? `Page file: ${b.page}` : null,
        b.id ? `Element: data-ui-id="${b.id}"` : null,
        b.code ? `Reason: ${b.code}` : null,
        `Error: ${b.message}`,
      ]
        .filter((line) => line !== null)
        .join("\n"),
  },
  actions: {
    undo: "Undo",
  },
  /** How the facts in a message are named. */
  named: {
    thatElement: "that element",
    pageName: (file: string) => file.replace(/^.*\//, "").replace(/\.[jt]sx$/, "").replace(/Page$/, "").replace(/([a-z])([A-Z])/g, "$1 $2") || file,
    pageComponent: (component: string) => component.replace(/Page$/, "").replace(/([a-z])([A-Z])/g, "$1 $2"),
    folder: (folder: string) => folder.replace(/\/+$/, "").replace(/^.*\//, ""),
  },
  common: {
    cancel: "Cancel",
    delete: "Delete",
  },
  app: {
    name: "Skeleton",
    closeProject: "Close project",
    info: (i: { appVersion: string; electron: string; node: string; platform: string }) => `v${i.appVersion} · Electron ${i.electron} · Node ${i.node} · ${i.platform}`,
    /** Licence notices for what Skeleton ships (moves to About with the ⋯ menu). */
    licences: "Icons: Lucide (ISC licence)",
    /** Why handles and the colour panel can't restyle an element: its tooltip and its message. */
    classEdits: {
      locked: (el: string) => `Can't restyle ${el}: it's agent code, so the agent's code decides its look.`,
      noId: (el: string) => `Can't restyle ${el} yet: ${OUTSIDE}`,
      agentClassName: (el: string) => `Can't restyle ${el}: the agent's code decides its look. Add a note to ask the agent.`,
      gone: "Can't do that: the element isn't on the page any more.",
    },
    unchecked: "Skeleton can't check changes against your app's code right now, so it won't notice if a change breaks your app. See Details.",
    thatElement: "that element",
    cantMoveThere: (name: string) => `Can't move into ${name} yet: ${OUTSIDE}`,
    nothingSelected: "Select an element first.",
    cantDropThere: (name: string) => `Can't drop into ${name} yet: ${OUTSIDE}`,
    canvas: "Canvas",
    selectMode: "Edit",
    interactMode: "Try it",
    history: "History",
    undo: "Undo",
    redo: "Redo",
    undoTitle: (edit: string) => `Undo ${edit} (Ctrl+Z)`,
    redoTitle: (edit: string) => `Redo ${edit} (Ctrl+Shift+Z)`,
    nothingToUndo: "There's nothing to undo.",
    nothingToRedo: "There's nothing to redo.",
    previewWidth: "Preview width",
    layouts: { desktop: "Desktop", tablet: "Tablet", mobile: "Mobile", "side-by-side": "Side by side" },
    colourMode: "App theme",
    light: "Light mode",
    dark: "Dark mode",
    noPageFile: (pathname: string) => `No page opens at ${pathname}.`,
    inspector: "Inspector",
    tabs: {
      element: () => "Element",
      tokens: () => "Theme",
      violations: (n: number) => `Off-theme${count(n)}`,
      pass: () => "Agent's work",
    },
    dialogFallback: "Dialog",
  },
  workspaces: {
    title: "Workspace",
    names: { build: "Build", style: "Style", handoff: "Hand off" },
    /** What each workspace is for, in the status bar. */
    purpose: {
      build: "Build: add elements and arrange them on the page",
      style: "Style: set the theme and fine-tune how elements look",
      handoff: "Hand off: review notes, hand the project to the agent, and review its work",
    },
  },
  left: {
    title: "Side panel",
    add: "Add",
    layers: "Layers",
    reach: "Drag a handle: every element of that kind changes. Hold Shift: the whole theme. Hold Alt: just this one.",
  },
  canvasBar: "Canvas",
  topBar: {
    page: (name: string) => `Page: ${name}`,
    noPage: "none",
    more: "More",
    appPreview: "App preview",
    about: "About Skeleton",
  },
  status: {
    /** The app's state, in the status bar. */
    app: (state: string): string =>
      ({
        running: "Your app is running",
        starting: "Starting your app…",
        installing: "Getting your app ready…",
        stopped: "Your app isn't running",
        crashed: "Your app stopped",
        failed: "Your app couldn't start",
      })[state] ?? "Your app isn't running",
  },
  picker: {
    open: "Open",
    openFolder: "Open…",
    openTitle: "Open a Skeleton project",
    noRecent: "No projects yet. Create one to get started.",
    recent: "Recent projects",
    missing: "(missing)",
    missingHint: "That folder isn't there any more. Forget it, or put the folder back.",
    forget: "Forget",
    forgetLabel: (name: string) => `Forget ${name}`,
    newProject: "New project",
    projectName: "Project name",
    inFolder: (dir: string) => `in ${dir}`,
    parentTitle: "Where should the project go?",
    change: "Change…",
    create: "Create project",
    creating: "Creating…",
    createProgress: "Creating your project. This takes about half a minute.",
  },
  canvas: {
    server: {
      starting: "Starting your app…",
      installing: "Getting your app ready…",
      stopped: "Your app isn't running. Start it from App preview in the ⋯ menu.",
      crashed: "Your app stopped. App preview in the ⋯ menu shows what happened.",
      failed: "Your app couldn't start. App preview in the ⋯ menu shows what happened.",
    } as Record<string, string>,
    withAgent: (round: number) => `Agent is working · round ${round}`,
    veil: "The agent is working on your project, so the canvas can't be changed. Take it back when the agent is done.",
    frameLabel: (width: string, pixels: number, scale: number) => `${width} · ${pixels}px${scale < 1 ? ` · ${Math.round(scale * 100)}%` : ""}`,
    updating: " · updating…",
    frameTitle: (width: string) => `Preview (${width})`,
  },
  colour: {
    title: "Colour",
    close: "Close colour",
    /** What the colour is used for on the element, and which theme value it is. */
    summary: (utility: string, name: string) => `${({ bg: "Background", text: "Text", border: "Border" } as Record<string, string>)[utility] ?? "Colour"}: ${name}`,
    scope: "Change",
    /** "light" or "dark", as the App theme calls it. */
    mode: (mode: string) => (mode === "dark" ? "dark mode" : "light mode"),
    token: (mode: string) => `Theme value (${copy.colour.mode(mode)})`,
    tokenTitle: (name: string, mode: string) => `Change ${name} (${copy.colour.mode(mode)}) everywhere it's used`,
    instance: "Just this one",
    instanceTitle: "A colour set by hand on this element: it shows as off-theme",
    /** The picker's parts. */
    area: "Colour: saturation across, brightness up",
    areaValue: (s: number, v: number) => `Saturation ${s}%, brightness ${v}%`,
    hue: "Hue",
    /** A swatch's readout: its hex, and its opacity when it isn't solid. */
    readout: (hex: string, opacity: number) => (opacity < 100 ? `${hex} · ${Math.round(opacity)}%` : hex),
    hex: "Hex",
    opacity: "Opacity %",
    red: "R",
    green: "G",
    blue: "B",
    hueShort: "H",
    saturation: "S",
    lightness: "L",
    valueLabel: (name: string, mode: string) => `${name}, ${copy.colour.mode(mode)}`,
    instanceNote: (_utility: string) => "Sets this colour on this element only. It shows in Off-theme.",
  },
  devServer: {
    title: "App preview",
    /** The app's state, as shown next to the panel's title. */
    state: (state: string): string =>
      ({ running: "Running", starting: "Starting…", installing: "Getting ready…", stopped: "Stopped", crashed: "Stopped unexpectedly", failed: "Couldn't start" })[state] ?? "Stopped",
    start: "Start",
    stop: "Stop",
  },
  pages: {
    title: "Pages",
    list: "Pages list",
    dynamic: "Its web address needs details from your app. Open it by going there in the app.",
    unreadable: "Skeleton can't read this page, so it can't be opened here.",
    missing: (_file: string) => "This page isn't in your app any more.",
    noName: "Page",
    add: "Add page",
    rename: "Rename",
    renameForm: "Rename page",
    name: "Page name",
    path: "Web address",
    submitAdd: "Add",
    confirmDeleteTitle: "Delete page",
    confirmDelete: (page: string, path: string) => `Delete the ${page} page? Its web address ${path} will stop working.`,
    deletePage: "Delete page",
  },
  palette: {
    title: "Add",
    missing: (missing: readonly string[]) => `This project doesn't have ${missing.join(", ")}.`,
    /** Group names, by the palette's group id. */
    groups: { layout: "Layout", inputs: "Inputs", display: "Display", overlay: "Overlays", navigation: "Navigation" } as Record<string, string>,
    groupList: (label: string) => `${label} elements`,
    /** Entry names and what they're for, by the palette's entry id. */
    items: {
      "stack-vertical": ["Column", "Items arranged one below another."],
      "stack-horizontal": ["Row", "Items side by side."],
      grid: ["Grid", "Items in equal columns."],
      container: ["Page width", "Centres its content and stops it getting too wide."],
      spacer: ["Push apart", "Takes up spare room in a Column or Row, pushing its neighbours apart."],
      button: ["Button", "Something to click that does an action."],
      input: ["Text field", "A one-line box for typing text."],
      textarea: ["Text box", "A box for typing several lines of text."],
      select: ["Pick list", "Choose one option from a list."],
      checkbox: ["Checkbox", "A tick box with a label."],
      switch: ["Switch", "An on/off toggle with a label."],
      form: ["Form", "Fields with labels and a send button. The agent makes it work."],
      card: ["Card", "A box with a title, for grouping content."],
      badge: ["Badge", "A small label, e.g. for a status."],
      avatar: ["Avatar", "A round picture, with initials when there's no picture."],
      table: ["Table", "Rows and columns of information."],
      tabs: ["Tabs", "Switch between panels by their tab."],
      separator: ["Separator", "A thin dividing line."],
      dialog: ["Dialog", "A box over the page, opened by its button."],
      sheet: ["Side panel", "A panel that slides in from the edge, opened by its button."],
      "dropdown-menu": ["Menu", "A list of actions, opened by its button."],
      toast: ["Pop-up message", "A short message that appears briefly and goes away by itself."],
      sidebar: ["Sidebar", "Navigation down the side, beside the page content."],
    } as Record<string, readonly [label: string, description: string]>,
    /** Why an entry can't be placed, by its id, where the palette gives one. */
    notes: {
      toast: "Pop-up messages are shown by the agent's code. Place the button that should show one, and add a note asking the agent to make it work.",
    } as Record<string, string>,
  },
  properties: {
    title: "Properties",
    noId: (el: string) => `Can't change ${el} yet: ${OUTSIDE}`,
    custom: (value: string) => `${value} (custom)`,
    agentSet: "decided by the agent's code",
    agentSetTitle: "The agent's code decides this; ask the agent to change it",
    text: "Text",
    grid: "Grid",
    agentLayout: "The agent's code decides its look, so its layout can't be changed here.",
    empty: "This element has no settings.",
  },
  selection: {
    title: "Selection",
    element: "Element",
    locked: "Agent code",
    agentLogic: "Agent controls",
    clickToSelect: "Click to select it.",
    nothing: "Click an element on the page to change it.",
    moveUp: "Move up",
    moveUpTitle: "Move up (Alt+↑)",
    moveDown: "Move down",
    moveDownTitle: "Move down (Alt+↓)",
    deleteTitle: "Delete (Del)",
    noTrigger: (name: string) => `Can't open it here: its button isn't on the canvas, so the app opens this ${name} some other way.`,
    openTitle: "Opens it the way your app does, with its button. Nothing in your project changes.",
    open: (name: string) => `Open ${name} in canvas`,
    close: (name: string) => `Close ${name}`,
    confirmDelete: "Confirm delete",
    deletesAgentCode: "This also deletes agent code the app may rely on:",
    deleteAnyway: "Delete anyway",
  },
  tokens: {
    title: "Theme",
    groups: { colour: "Colours", radius: "Corners", spacing: "Spacing", type: "Text sizes", font: "Fonts", border: "Lines" },
    filterLabel: "Find a theme value",
    filter: "Find",
    countTitle: "Elements on this page that use it",
    /** A theme value's field: its name, plus the mode when it differs between light and dark. */
    valueLabel: (name: string, mode?: "light" | "dark" | null) => (mode ? `${name}, ${mode} mode` : name),
    derivedTitle: "Follows other theme values: it changes when they do",
    resolved: (value: string | null) => `= ${value ?? "…"}`,
    cantDetach: "It doesn't come to one value, so it can't be given its own value here",
    detachTitle: (value: string) => `Stop following and set it to ${value}`,
    detach: "Set own value",
    detached: "Own value",
    attachTitle: (_formula: string | null) => "Follow the theme values it came from again",
    attach: "Follow again",
  },
  violations: {
    title: "Off-theme",
    property: {
      radius: "corners",
      spacing: "spacing",
      "font-size": "text size",
      "border-width": "line thickness",
      colour: "colour",
      style: "look set in the agent's code",
      other: "custom value",
    },
    empty: "Everything follows the theme.",
    showKeptLabel: "Show left as is",
    showKept: (n: number): string => `${copy.violations.showKeptLabel} (${n})`,
    nearest: "Closest theme value:",
    nearestValue: (name: string, value: string) => `${name} (${value})`,
    noElement: "An element Skeleton can't point to",
    inAgentCode: "It's in agent code: ask the agent to change it, or leave it as is.",
    snap: "Use closest",
    snapTitle: (name: string) => `Use ${name} instead`,
    promote: "Add to theme",
    keep: "Leave as is",
    keepTitle: "Stop listing it here",
    promoteForm: "Add to theme",
    tokenName: "Theme value name",
    namePlaceholder: "e.g. brand",
    needName: "Type a name for the new theme value first.",
    badName: "A theme value name starts with a lowercase letter and uses lowercase letters, numbers and dashes, like brand or brand-dark.",
    create: "Save",
  },
  viewSource: {
    show: "Show code",
    hide: "Hide code",
    title: "Page code",
    where: (file: string, start: number, end: number) => `${file}:${start}–${end} · read-only`,
  },
  toasts: {
    dismiss: "Dismiss",
  },
  layers: {
    title: "Layers",
    tree: "Layers tree",
    offscreen: "Not rendered on the canvas right now",
    expand: "Expand",
    collapse: "Collapse",
    locked: "agent code",
  },
  /** Why an element can't be moved or deleted: the disabled button's tooltip and the message. */
  nodes: {
    lockedLogic: (kind: string) => kind,
    protectedLogic: (controls: readonly string[], element: string) => `${controls.join(", ")} of ${element}`,
    gone: "Can't do that: the element isn't on the page any more.",
    rootRemove: (el: string) => `Can't delete ${el}: it holds the whole page.`,
    insideLockedRemove: (el: string, kind: string) => `Can't delete ${el} on its own: it's inside agent code (${kind}). You can delete the whole ${kind} instead.`,
    noIds: (el: string) => `Can't delete ${el} yet: ${OUTSIDE}`,
    noIdsMove: (el: string) => `Can't move ${el} yet: ${OUTSIDE}`,
    rootMove: (el: string) => `Can't move ${el}: it holds the whole page.`,
    insideLockedMove: (el: string, kind: string) => `Can't move ${el} on its own: it's inside agent code (${kind}). You can move the whole ${kind} instead.`,
    noId: (el: string, parent: string) => `Can't move ${el} yet: ${parent} ${OUTSIDE_PARENT}`,
    first: (el: string) => `${el} is already first.`,
    last: (el: string) => `${el} is already last.`,
  },
  notes: {
    title: "Notes",
    onElement: "Notes on this element",
    types: { build: "Build", behaviour: "Behaviour", question: "Question" },
    readOnly: "The agent is working: notes can be changed again after Take back.",
    cantPin: (name: string) => `Can't pin a note to ${name} yet: ${OUTSIDE}`,
    selectToPin: "To add a note, select an element: its notes are at the end of the Element tab.",
    type: "Note type",
    status: "Note status",
    all: "All",
    statusFilter: { open: "Open", resolved: "Resolved", all: "All" },
    focusOn: "On",
    focusOnly: "only",
    showAll: "Show every element's notes",
    empty: "No notes yet. Select an element and add a note for the agent.",
    otherReplies: "Other agent replies",
    replyPass: (round: number) => `(round ${round})`,
    orphaned: (n: number) => `Notes without an element (${n})`,
    orphanedHint: "Their elements were deleted. Attach each to another element, or delete it.",
    wasOn: (target: string) => `was on ${target}`,
    attach: "Attach to selected",
    attachTitle: (name: string) => `Attach to ${name}`,
    attachNeedsId: "Select an element to attach it to first",
    discard: "Delete",
    addForm: "Add a note",
    noteOn: (name: string) => `Note on ${name}`,
    text: "Note text",
    askPlaceholder: "Ask the agent…",
    taskPlaceholder: "What should the agent do?",
    add: "Add",
    element: "Element",
    resolvedStatus: "resolved",
    openStatus: "open",
    sentIn: (round: number) => `handed off in round ${round}`,
    agentReply: (round: number) => `Agent, round ${round}:`,
    resolve: "Resolve",
    reopen: "Reopen",
  },
  loop: {
    title: "Hand off",
    busy: {
      handoff: "Handing off: checking your app still works…",
      takeBack: "Taking back: reviewing the agent's work…",
      revert: "Undoing the agent's work…",
    },
    withAgent: (round: number | undefined) => `Agent is working · round ${round}`,
    withYou: "With you",
    handOff: "Hand off",
    handOffHint: (next: number, open: number) =>
      `Round ${next}: ${open} open ${plural(open, "note")} ${plural(open, "goes", "go")} to the agent.`,
    takeBack: "Take back",
    review: "Review the agent's work",
    takeBackHint: "Ask your agent to work on the project (your notes are its to-do list), then take it back here.",
  },
  pass: {
    title: "Agent's work",
    numbered: (n: number) => `Round ${n}`,
    emptyWithAgent: "The agent's work shows here after you take the project back.",
    empty: "The agent's work shows here after you take the project back.",
    noSummary: "Taken back in an earlier session: only what the agent changed is kept.",
    revertButton: (n: number) => `Undo the agent's work in round ${n}…`,
    revertTitle: "Undo the agent's work",
    revertConfirm: (n: number) =>
      `Put the project back as it was when you handed it off in round ${n}? The agent's work and your changes since are saved in the project's history first.`,
    revert: "Undo the agent's work",
    buildPassed: "Your app still works",
    buildPasses: (ms: number): string => `${copy.pass.buildPassed} (checked in ${(ms / 1000).toFixed(1)} s)`,
    buildFails: "Your app has a problem in its code and won't start. Ask the agent to fix it.",
    tasks: (resolved: number, sent: number, unmatched: number) =>
      `Notes: ${resolved} of ${sent} done${unmatched ? `; the agent ticked ${unmatched} ${plural(unmatched, "item")} that ${plural(unmatched, "matches", "match")} no note` : ""}`,
    replies: (n: number) => (n ? ` · ${n} ${plural(n, "reply", "replies")}` : ""),
    groups: {
      breaches: "Rules the agent broke",
      repaired: "Fixed by Skeleton",
      files: "Files changed",
      added: "Elements added",
      removed: "Elements removed",
      violations: "New off-theme values",
      locked: "New agent code",
      parseErrors: "Files Skeleton can't read",
    },
    rule: (rule: string | number) => `Rule ${rule}:`,
    onPage: (page: string) => `on the ${page} page`,
    reminted: "Told apart from a copy: ",
    gaveId: "Named so Skeleton can find it: ",
    fileChange: (status: string, additions: number, deletions: number) =>
      `${status === "added" ? "new " : status === "deleted" ? "deleted " : ""}+${additions} −${deletions}`,
    orphaned: (n: number) => `${n} ${plural(n, "note has", "notes have")} no element now: see Notes without an element.`,
    inlineStyle: "Look set in the agent's code",
    diffTitle: "What the agent changed",
    noChanges: "The agent changed nothing.",
    lineCounts: (additions: number, deletions: number) => `+${additions} −${deletions}`,
  },
} as const;
