/**
 * Every word the renderer shows on screen (T8.1, docs/ui-refresh-spec.md §5).
 * Panels read their text from here, and so do the e2e helpers, so a wording
 * change is made once. Templated text is a function of what it shows.
 */

import type { ReasonCode } from "@skeleton/app-main/ipc";

/** What a reason's sentence can name, already in plain words (messages.ts fills it in). */
export interface Named {
  /** An element, by its element name. */
  el: string;
  /** A page, by its page name. */
  page: string;
  /** A web address. */
  path: string;
  /** A page or project name the user typed. */
  name: string;
  /** A theme value, by its theme value name. */
  theme: string;
  round: number;
  max: number;
  /** An undo step's label. */
  edit: string;
  direction: "undo" | "redo";
  /** A folder, by its own name. */
  folder: string;
  /** The web address a page's address must start with. */
  parent: string;
}

const count = (n: number) => (n > 0 ? ` (${n})` : "");
/** `word` or `plural` (default `word` + "s") for `n`. */
const plural = (n: number, word: string, many = `${word}s`) => (n === 1 ? word : many);

export const copy = {
  /**
   * The plain sentence for every reason code (ADR 013, spec §4): what happened, then
   * what to do. Refusals and problems; anything else gets `fault`.
   */
  messages: {
    "inside-agent-code": (n) => `Can't change ${n.el}: it's inside agent code. You can move or delete the whole agent code instead.`,
    "is-agent-code": (n) => `Can't change ${n.el}: it's agent code, so Skeleton won't rewrite it. You can move or delete it whole.`,
    "agent-control": (n) => `Can't change that setting of ${n.el}: the agent's code decides it.`,
    "agent-style": (n) => `Can't restyle ${n.el}: the agent's code decides its look. Add a note to ask the agent.`,
    "agent-value": () => "Can't edit this text: the agent's code fills it in.",
    "text-has-elements": (n) => `Can't edit the text of ${n.el} as a whole: it holds other elements. Edit their text instead.`,
    "text-has-comment": () => "Can't edit this text here: the agent left a remark in it. Ask the agent to change it.",
    "text-too-long": (n) => `That text is too long. Use at most ${n.max} characters.`,
    "element-gone": () => "Can't do that: the element isn't on the page any more.",
    "move-into-itself": (n) => `Can't move ${n.el} into itself.`,
    "next-to-text": (n) => `Can't drop there: ${n.el} holds text, so nothing can go inside it.`,
    "with-agent": () => "The project is with the agent. Take it back first.",
    "edit-undone": () => "Skeleton undid that change because it would have broken your app. Nothing was changed.",
    "nothing-to-undo": (n) => `There's nothing to ${n.direction}.`,
    "changed-since": (n) =>
      `Can't ${n.direction} "${n.edit}": the ${n.page} page has changed since then, probably by the agent. ${n.direction === "undo" ? "Undoing" : "Redoing"} now would lose that change.`,
    "bad-web-address": () => "A web address uses lowercase words and dashes, like /orders or /orders/archive.",
    "web-address-taken": (n) => `There's already a page at ${n.path}. Pick another web address.`,
    "web-address-outside": (n) => `This page's web address has to start with ${n.parent}.`,
    "bad-page-name": () => "A page name starts with a letter and uses only letters, numbers and spaces, like Order history.",
    "page-name-taken": (n) => `There's already a page called ${n.name}. Pick another name.`,
    "page-name-in-code": () => "Can't use that name: the page's code already uses it. Pick another name.",
    "page-file-taken": (n) => `There's already a page called ${n.page}. Pick another name.`,
    "only-page": () => "Can't delete the only page. Add another page first.",
    "page-used-elsewhere": (n) => `Can't do that to the ${n.page} page: other parts of your app use it. Ask the agent to remove those first.`,
    "page-has-subpages": (n) => `Can't do that to the page at ${n.path}: it has pages inside it. Ask the agent to change it.`,
    "page-is-default": () => "Can't change this page's web address: it shares the web address of the pages around it.",
    "page-not-renamable": () => "Can't rename this page here: the agent set it up in a way Skeleton can't change. Ask the agent to rename it.",
    "page-missing": () => "That page isn't in your app any more.",
    "page-unreadable": (n) => `Skeleton can't read the ${n.page} page right now, so it can't be changed.`,
    "pages-unreadable": () => "Skeleton can't read your app's list of pages, so pages can't be changed right now.",
    "theme-unreadable": () => "Skeleton can't read your app's theme right now.",
    "bad-theme-value": (n) => `That isn't a value ${n.theme} can use. Type one value, like 12px or #3366cc.`,
    "theme-value-twice": (n) => `Can't change ${n.theme}: the theme sets it in more than one place.`,
    "theme-value-missing": (n) => `Can't change ${n.theme}: it isn't in the theme any more.`,
    "theme-name-taken": (n) => `There's already a theme value called ${n.theme}. Pick another name.`,
    "off-theme-moved": () => "That value has moved since the list was made. Try again.",
    "off-theme-in-agent-code": () => "Can't change this value: it's in agent code. Leave it as is, or ask the agent.",
    "already-handed-off": (n) => `The project is already with the agent (round ${n.round}). Take it back first.`,
    "not-handed-off": () => "There's nothing to take back: the project isn't with the agent.",
    "nothing-to-undo-agent": () => "There's no agent's work to undo: the last step wasn't a take back.",
    "duplicate-ids": () => "Can't hand off yet: two elements look the same to Skeleton, so it can't tell them apart.",
    "build-broken": () => "Can't hand off: your app has a problem in its code and won't start.",
    "file-unreadable": () => "Skeleton can't read one of your app's pages, so it can't go on. Ask the agent to fix it, then try again. Nothing was changed.",
    "notes-unreadable": () => "Skeleton can't read your notes. Ask the agent to fix them, then try again. Nothing was changed.",
    "note-element-gone": () => "Can't pin the note there: that element isn't in your app any more.",
    "not-a-skeleton-project": (n) => `${n.folder} wasn't made with Skeleton, so it can't be opened here.`,
    "bad-project-name": () => "A project name starts with a letter or number, and uses letters, numbers, spaces and dashes.",
    "project-exists": (n) => `There's already a folder called ${n.folder} there. Pick another name or place.`,
    "folder-missing": () => "That folder isn't there any more. Choose another place.",
    "create-failed": () => "Skeleton couldn't create the project. Nothing was left behind.",
  } satisfies Record<ReasonCode, (n: Named) => string>,
  /** Anything without a reason: only a Skeleton bug could cause it. */
  fault: {
    unchanged: "Skeleton couldn't do that. Nothing in your project was changed.",
    unknown: "Skeleton couldn't do that. Something went wrong; see Details.",
  },
  details: {
    show: "Details",
    hide: "Hide details",
    copy: "Copy details",
    copied: "Copied",
    /** The block Copy details puts on the clipboard, for pasting to the agent. */
    block: (b: { tried: string; page: string | null; id: string | null; code: string | null; message: string }) =>
      [
        `Skeleton couldn't do this: ${b.tried}`,
        b.page ? `Page file: ${b.page}` : null,
        b.id ? `Element: data-ui-id="${b.id}"` : null,
        b.code ? `Reason: ${b.code}` : null,
        `Error: ${b.message}`,
      ]
        .filter((line) => line !== null)
        .join("\n"),
  },
  actions: {
    undo: "Undo",
  },
  /** How the facts in a message are named. */
  named: {
    thatElement: "that element",
    elementName: (kind: string, text: string | null) => (text ? `${kind} "${text}"` : kind),
    pageName: (file: string) => file.replace(/^.*\//, "").replace(/\.[jt]sx$/, "").replace(/Page$/, "").replace(/([a-z])([A-Z])/g, "$1 $2") || file,
    pageComponent: (component: string) => component.replace(/Page$/, "").replace(/([a-z])([A-Z])/g, "$1 $2"),
    folder: (folder: string) => folder.replace(/\/+$/, "").replace(/^.*\//, ""),
  },
  common: {
    cancel: "Cancel",
    delete: "Delete",
  },
  app: {
    name: "Skeleton",
    closeProject: "Close project",
    info: (i: { appVersion: string; electron: string; node: string; platform: string }) => `v${i.appVersion} · Electron ${i.electron} · Node ${i.node} · ${i.platform}`,
    classEdits: {
      locked: "it's a locked block: its classes are agent code",
      noId: "it has no data-ui-id",
      agentClassName: "its className is set by agent code",
      gone: "it isn't on the page any more",
    },
    unchecked: (reason: string) => `Edits aren't being typechecked: ${reason}`,
    cantChange: (reason: string) => `Can't change this element: ${reason}`,
    thatElement: "that element",
    cantMoveThere: (name: string) => `Can't move there: ${name} has no data-ui-id.`,
    cantMove: (name: string, reason: string) => `Can't move ${name}: ${reason}`,
    cantDelete: (reason: string | null) => `Can't delete: ${reason}`,
    nothingSelected: "nothing selected",
    cantDropThere: (name: string) => `Can't drop there: ${name} has no data-ui-id.`,
    canvas: "Canvas",
    selectMode: "Select mode",
    interactMode: "Interact mode",
    history: "History",
    undo: "Undo",
    redo: "Redo",
    undoTitle: (edit: string) => `Undo ${edit} (Ctrl+Z)`,
    redoTitle: (edit: string) => `Redo ${edit} (Ctrl+Shift+Z)`,
    nothingToUndo: "Nothing to undo",
    nothingToRedo: "Nothing to redo",
    previewWidth: "Preview width",
    layouts: { desktop: "Desktop", tablet: "Tablet", mobile: "Mobile", "side-by-side": "Side by side" },
    colourMode: "Colour mode",
    light: "Light",
    dark: "Dark",
    noPageFile: (pathname: string) => `No page file for ${pathname}.`,
    inspector: "Inspector",
    tabs: {
      element: () => "Element",
      tokens: () => "Tokens",
      violations: (n: number) => `Violations${count(n)}`,
      notes: (n: number) => `Notes${count(n)}`,
      pass: () => "Pass",
    },
    dialogFallback: "Dialog",
  },
  picker: {
    open: "Open",
    openFolder: "Open…",
    openTitle: "Open a Skeleton project",
    noRecent: "No recent projects.",
    recent: "Recent projects",
    missing: "(missing)",
    forget: "Forget",
    forgetLabel: (name: string) => `Forget ${name}`,
    newProject: "New project",
    projectName: "Project name",
    inFolder: (dir: string) => `in ${dir}`,
    parentTitle: "Where should the project go?",
    change: "Change…",
    create: "Create project",
    creating: "Creating…",
    createProgress: "Writing files, installing dependencies, making the first commit…",
  },
  canvas: {
    server: {
      starting: "Starting the dev server…",
      installing: "Installing dependencies…",
      stopped: "The dev server isn't running.",
      crashed: "The dev server stopped unexpectedly. See the log below.",
      failed: "The dev server couldn't start. See the log below.",
    } as Record<string, string>,
    withAgent: (handoff: number) => `With agent · handoff #${handoff}`,
    veil: "The canvas is locked while your agent works. Press Take back when it's done.",
    frameLabel: (width: string, pixels: number, scale: number) => `${width} · ${pixels}px${scale < 1 ? ` · ${Math.round(scale * 100)}%` : ""}`,
    updating: " · updating…",
    frameTitle: (width: string) => `Preview (${width})`,
  },
  colour: {
    title: "Colour",
    close: "Close colour",
    summary: (utility: string, name: string, token: string) => `${utility}-${name} · ${token}`,
    scope: "Colour scope",
    token: (mode: string) => `Token (${mode})`,
    tokenTitle: (token: string, mode: string) => `Edit ${token} (${mode})`,
    instance: "This element",
    instanceTitle: "An arbitrary colour on this element: a violation",
    pick: "Pick colour",
    valueLabel: (token: string, mode: string) => `${token} ${mode} value`,
    instanceNote: (utility: string) => `Writes ${utility}-[#…] on this element: an override the violations panel lists.`,
  },
  devServer: {
    title: "Dev server",
    /** The server's state, as shown next to its title. */
    state: (state: string) => state,
    start: "Start",
    stop: "Stop",
  },
  pages: {
    title: "Pages",
    list: "Pages list",
    dynamic: "Needs route parameters; open it by navigating in the app",
    unreadable: "Not a page file Skeleton can read",
    missing: (file: string) => `${file} is missing`,
    add: "Add page",
    rename: "Rename",
    renameForm: "Rename page",
    name: "Name",
    path: "Path",
    submitAdd: "Add",
    confirmDeleteTitle: "Confirm delete page",
    confirmDelete: "Delete",
    confirmAnd: "and",
    deletePage: "Delete page",
  },
  palette: {
    title: "Palette",
    missing: (missing: readonly string[]) => `This project doesn't have ${missing.join(", ")}.`,
    /** Labels from the palette itself, shown as they come for now. */
    groupLabel: (label: string) => label,
    groupList: (label: string) => `${label} components`,
    itemLabel: (label: string) => label,
    itemDescription: (description: string) => description,
  },
  properties: {
    title: "Properties",
    noId: "This element has no data-ui-id, so Skeleton can't edit it.",
    /** A setting's label: its prop name, for now. */
    propLabel: (name: string) => name,
    /** An option of an enum setting: its value, for now. */
    optionLabel: (_prop: string, option: string) => option,
    custom: (value: string) => `${value} (custom)`,
    agentSet: "set by agent code",
    agentSetTitle: "Set by agent code; edit it in code",
    text: "Text",
    grid: "Grid",
    stack: "Stack",
    agentLayout: "Its classes are set by agent code, so layout is edited in code.",
    /** Layout class groups and their options come labelled from the palette. */
    classGroupLabel: (label: string) => label,
    classOptionLabel: (label: string) => label,
    empty: "No properties to edit here.",
  },
  selection: {
    title: "Selection",
    element: "Element",
    kind: "Kind",
    id: "ID",
    noId: "none",
    locked: "Locked",
    agentLogic: "Agent logic",
    clickToSelect: "Click to select.",
    nothing: "Nothing selected.",
    moveUp: "Move up",
    moveUpTitle: "Move up (Alt+↑)",
    moveDown: "Move down",
    moveDownTitle: "Move down (Alt+↓)",
    deleteTitle: "Delete (Del)",
    noTrigger: (name: string) => `Its trigger isn't on the canvas: the app opens this ${name} some other way.`,
    openTitle: "Opens it the way the app does, by its trigger; the code doesn't change.",
    open: (name: string) => `Open ${name} in canvas`,
    close: (name: string) => `Close ${name}`,
    confirmDelete: "Confirm delete",
    deletesAgentCode: "This deletes agent code too:",
    deleteAnyway: "Delete anyway",
  },
  tokens: {
    title: "Tokens",
    groups: { colour: "Colour", radius: "Radius", spacing: "Spacing", type: "Type", font: "Font", border: "Border width" },
    filterLabel: "Filter tokens",
    filter: "Filter",
    /** A token as shown in its row: its CSS name, for now. */
    tokenName: (name: string) => name,
    countTitle: "Elements on this page it affects",
    valueLabel: (name: string) => `${name} value`,
    darkValueLabel: (name: string) => `${name} dark value`,
    derivedTitle: "Derived: follows the tokens it refers to",
    resolved: (value: string | null) => `= ${value ?? "…"}`,
    cantDetach: "It doesn't come to a single value, so it can't be detached here",
    detachTitle: (value: string) => `Replace the formula with ${value}`,
    detach: "Detach",
    detached: "Detached",
    attachTitle: (formula: string | null) => `Back to ${formula}`,
    attach: "Attach",
  },
  violations: {
    title: "Violations",
    property: {
      radius: "radius",
      spacing: "spacing",
      "font-size": "font size",
      "border-width": "border width",
      colour: "colour",
      style: "inline style",
      other: "arbitrary value",
    },
    empty: "No overrides: everything is styled with tokens.",
    showKeptLabel: "Show kept",
    showKept: (n: number): string => `${copy.violations.showKeptLabel} (${n})`,
    element: (name: string, id: string | null) => `${name}${id ? ` #${id}` : ""}`,
    nearest: "nearest:",
    nearestValue: (token: string, value: string) => `(${token} = ${value})`,
    inAgentCode: "In agent code: fix it in code, or keep it.",
    snap: "Snap",
    snapTitle: (utility: string) => `Replace with ${utility}`,
    promote: "Promote",
    keep: "Keep",
    keepTitle: "Acknowledge it and leave it (skeleton/config.json)",
    promoteForm: "Promote to token",
    tokenName: "Token name",
    namePlaceholder: "name",
    create: "Create",
  },
  viewSource: {
    show: "View source",
    hide: "Hide source",
    title: "Source",
    where: (file: string, start: number, end: number) => `${file}:${start}–${end} · read-only`,
  },
  toasts: {
    dismiss: "Dismiss",
  },
  layers: {
    title: "Layers",
    tree: "Layers tree",
    offscreen: "Not rendered on the canvas right now",
    expand: "Expand",
    collapse: "Collapse",
    locked: "locked",
  },
  nodes: {
    lockedLogic: (element: string, reason: string) => `🔒 ${element} (${reason})`,
    protectedLogic: (props: readonly string[], element: string) => `${props.join(", ")} on ${element}`,
    gone: "It's no longer on the page.",
    rootRemove: "The page's root element can't be removed.",
    insideLockedRemove: (name: string) => `It's inside 🔒 ${name}, agent code that uses it: edit it in place, or delete the whole block.`,
    noIds: "Neither it nor its parent has a data-ui-id.",
    rootMove: "The page's root element can't be moved.",
    insideLockedMove: (name: string) => `It's inside 🔒 ${name}: edit it in place.`,
    noId: (name: string) => `${name} has no data-ui-id.`,
    first: "It's already first.",
    last: "It's already last.",
  },
  notes: {
    title: "Notes",
    types: { build: "Build", behaviour: "Behaviour", question: "Question" },
    readOnly: "With the agent: notes can be changed again after Take back.",
    cantPin: (name: string) => `${name} has no data-ui-id, so notes can't be pinned to it.`,
    selectToPin: "Select an element to pin a note to it.",
    type: "Note type",
    status: "Note status",
    all: "All",
    statusFilter: { open: "Open", resolved: "Resolved", all: "All" },
    focusOn: "On",
    focusOnly: "only",
    showAll: "Show every element's notes",
    empty: "No notes here.",
    otherReplies: "Other agent replies",
    replyPass: (pass: number) => `(pass ${pass})`,
    orphaned: (n: number) => `Orphaned (${n})`,
    orphanedHint: "Their elements are gone. Attach each to another element, or discard it.",
    wasOn: (target: string) => `was on ${target}`,
    attach: "Attach to selected",
    attachTitle: (name: string | undefined, id: string) => `Attach to ${name} #${id}`,
    attachNeedsId: "Select an element with a data-ui-id first",
    discard: "Discard",
    addForm: "Add a note",
    noteOn: (name: string, target: string) => `Note on ${name} #${target}`,
    text: "Note text",
    askPlaceholder: "Ask the agent…",
    taskPlaceholder: "What should the agent do?",
    add: "Add",
    element: "element",
    resolvedStatus: "resolved",
    openStatus: "open",
    sentIn: (handoff: number) => `sent in #${handoff}`,
    agentReply: (pass: number) => `Agent, pass ${pass}:`,
    resolve: "Resolve",
    reopen: "Reopen",
  },
  loop: {
    title: "Handoff",
    busy: {
      handoff: "Handing off… (checking the build)",
      takeBack: "Taking back… (analysing and building)",
      revert: "Reverting the pass…",
    },
    withAgent: (handoff: number | undefined) => `With agent · handoff #${handoff}`,
    withYou: "With you",
    handOff: "Hand off",
    handOffHint: (next: number, open: number) =>
      `Handoff #${next}: ${open} open ${plural(open, "note")} ${plural(open, "goes", "go")} to the agent as tasks in HANDOFF.md.`,
    takeBack: "Take back",
    takeBackHint: "Run your agent on the project (its tasks are in HANDOFF.md), then take it back here.",
  },
  pass: {
    title: "Pass",
    numbered: (n: number) => `Pass #${n}`,
    emptyWithAgent: "The agent's pass shows here after Take back.",
    empty: "No pass to review: take one back first.",
    noSummary: "Taken back in an earlier session: the summary isn't kept, but the diff is.",
    revertButton: (n: number) => `Revert pass #${n}…`,
    revertTitle: "Revert pass",
    revertConfirm: (n: number) =>
      `Put the project back as it was at handoff #${n}? The agent's work and your edits since take-back are committed first, so they stay in git history.`,
    revert: "Revert",
    elementRef: (element: string, id: string) => `${element} #${id}`,
    buildPassed: "Build passes",
    buildPasses: (ms: number): string => `${copy.pass.buildPassed} (${(ms / 1000).toFixed(1)} s)`,
    buildFails: "Build fails",
    tasks: (resolved: number, sent: number, unmatched: number) =>
      `Tasks: ${resolved} of ${sent} done${unmatched ? `; ${unmatched} ticked ${plural(unmatched, "task")} matched no note` : ""}`,
    replies: (n: number) => (n ? ` · ${n} ${plural(n, "reply", "replies")}` : ""),
    groups: {
      breaches: "Contract breaches",
      repaired: "Repaired",
      files: "Files changed",
      added: "Elements added",
      removed: "Elements removed",
      violations: "New violations",
      locked: "New locked blocks",
      parseErrors: "Files that don't parse",
    },
    rule: (rule: string | number) => `Rule ${rule}:`,
    reminted: (was: string | null) => `Re-minted duplicate ${was} → `,
    gaveId: "Gave an ID: ",
    fileChange: (status: string, additions: number, deletions: number) => `${status === "modified" ? "" : `${status} `}+${additions} −${deletions}`,
    orphaned: (n: number) => `${n} ${plural(n, "note is", "notes are")} orphaned: see the tray in Notes.`,
    inlineStyle: "style={…}",
    diffTitle: "Diff against the handoff",
    noChanges: "The agent changed nothing.",
    lineCounts: (additions: number, deletions: number) => `+${additions} −${deletions}`,
  },
} as const;
